### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by bosmasan** [HommiePeter/homebridge-toon-platform#1]
I'm new at this so probably I do something wrong..

When i put "https://api.toon.eu/toonapi-accesstoken?tenant_id=eneco&client_id=<consumer_key>" in my browser I get this message: {"fault":{"faultstring":"Invalid ApiKey","detail":{"errorcode":"oauth.v2.InvalidApiKey"}}}

I figured I had to use my eneco client number instead of <consumer_key> but maybe that's wrong?

Or do I need additional settings in my account or Toon device?

Appreciatie your help.

**Comment by HommiePeter** [comment]
Hello bosmasan,

you can't use your Eneco client number instead of <consumer_key>. You must register (free of charge) your self for a developer account  (see https://developer.toon.eu). Once registered, you can define a virtual app which will provide you with a consumer key. Hope this information helps your further.

**Comment by HommiePeter** [comment]
If you do not agree please feel free to reopen the issue. 

Kind regards

Peter

**Comment by bosmasan** [comment]
It’s ok to close it. But i tried several times but there is no response from eneco to obtain a developers account. Too bad…

Op 29 jul. 2021 om 19:48 heeft HommiePeter ***@***.***> het volgende geschreven:

﻿
If you do not agree please feel free to reopen the issue.

Kind regards

Peter
