### ISSUE TITLE
Boxx Engie Belgium

### ISSUE THREAD

**Issue by rereone** [HommiePeter/homebridge-toon-platform#3]
Bonjour,

Est ce compatible avec la Boxx en Belgique ?

Hello,
Is it Worked with the Engie Boxx in Belgium ?

Thanks.

**Comment by HommiePeter** [comment]
Dear Rereone, 

i have only tested it with Toon that is offered by Eneco in The Netherlands. I am aware that a similar solution is offered in Belgium as well, but I don not have any detailed information, nor the setup to test it. So for now I would say that only Toon is supported. But if you could provide my with some more detailed information on the Boxx (which looks very similar to Toon) I could always look into it.

**Comment by rereone** [comment]
Hello, 

Thanks you in advance if you do it. 

What do you need ?
For me, thé are the same thermostat.

Kind Regards.

**Comment by JefNewTech** [comment]
Hello, 

I also have the Boxx from engie electrabel in Belgium. 
I would like to help you to integrate it to homebridge. 

Tell me what you need. 

if it can help on the side of homeassistant there is this 
[https://github.com/home-assistant/core/tree/ecb921949a9a6da8932013737a3b8fc079614ccb/homeassistant/components/toon](url)

**Comment by HommiePeter** [comment]
> Hello,
> 
> Thanks you in advance if you do it.
> 
> What do you need ? For me, thé are the same thermostat.
> 
> Kind Regards.

Hello Rereone I have looked at the de Boxx van Engie and it looks very similar to the Eneco Toon in The Netherlands. Like JefNewTech is also stating on the Home Assistant platform it was possible to obtain information of a Engie Boxx setup by means of the Toon integration available on Home Assistant. This might be an indication that the available Toon API's could also work for the Boxx from Engie. To try this experiment it would be good to see if you can register at https://developer.toon.eu/ and obtain a consumer key and consumer secret. Please let me know if it succeeds

**Comment by HommiePeter** [comment]
> Hello,
> 
> I also have the Boxx from engie electrabel in Belgium. I would like to help you to integrate it to homebridge.
> 
> Tell me what you need.
> 
> if it can help on the side of homeassistant there is this [https://github.com/home-assistant/core/tree/ecb921949a9a6da8932013737a3b8fc079614ccb/homeassistant/components/toon](url)

Hello Jef, 

i am aware of the Toon integration on the Home Assistant platform and that people use if for not only Toon but also the Engie Electrabel Boxx solution and Viesgo Toon. Because of the switch to the OAuth authorisation model a lof of people are having difficulties in making the integration work for them within HomeAssistant (it took my self also some puzzling). What is still in doubt for myself is if the change on Quby side was broader (not only OAuth) but also no longer allowing non Eneco Toon users to make use of the API' s. Like I also suggested to rereone first step would be to see if you can register at https://developer.toon.eu to see if you can retrieve a consumer key and concumer secret. If that works we are a big step closer in making the homebridge plug also work for the Engie Boxx. Let me know if you where able to register

**Comment by JefNewTech** [comment]
Hello
Thank you for your answer. 
For my part, I have my accesses on the site https://developer.toon.eu/
I have created my application and I have my access keys. 
Tell me if I can still help for other information

**Comment by rereone** [comment]
Hello, 

Thanks.

I have my access too on the site, I created a application and I have too mys access.

**Comment by HommiePeter** [comment]
> Hello
> Thank you for your answer.
> For my part, I have my accesses on the site https://developer.toon.eu/
> I have created my application and I have my access keys.
> Tell me if I can still help for other information

Hello JefNewTech, 

what you now should do is try to create a API_Token this can be done via the following statement in for example your browser.

https://api.toon.eu/toonapi-accesstoken?tenant_id=eneco&client_id=<consumer_key>

Where tenant_id=eneco should for Engie Boxx users be replaced by tentant_id=electrabel 
and consumer_key should be the consumer key that you received during application registration at developer.toon.eu. After that your will be requested to login to your Electrabel Engie Boxx account an a token will be generated (text string). This token need to be safe stored since you need it to for this plugin.   

Please let me know it the above mentioned steps lead to re required out come (a generated API Token for your Electrabel Engie Boxx).

**Comment by HommiePeter** [comment]
> Hello,
> 
> Thanks.
> 
> I have my access too on the site, I created a application and I have too mys access.

Hello rereone, 

what you now should do is try to create a API_Token this can be done via the following statement in for example your browser.

https://api.toon.eu/toonapi-accesstoken?tenant_id=eneco&client_id=<consumer_key>

Where tenant_id=eneco should for Engie Boxx users be replaced by tentant_id=electrabel 
and consumer_key should be the consumer key that you received during application registration at developer.toon.eu. After that your will be requested to login to your Electrabel Engie Boxx account an a token will be generated (text string). This token need to be safe stored since you need it to for this plugin.   

Please let me know it the above mentioned steps lead to re required out come (a generated API Token for your Electrabel Engie Boxx).

**Comment by JefNewTech** [comment]
I can't find the engie page so my login is not recognized 
![image](https://user-images.githubusercontent.com/8571116/151367094-e77ecb54-7356-4c71-b920-92c4599fb0f6.png)

**Comment by HommiePeter** [comment]
> I can't find the engie page so my login is not recognized
> ![image](https://user-images.githubusercontent.com/8571116/151367094-e77ecb54-7356-4c71-b920-92c4599fb0f6.png)

Dear JefNewTech,

did you try using your Boxx mobile app credentials ?

**Comment by JefNewTech** [comment]
> > I can't find the engie page so my login is not recognized
> 
> > ![image](https://user-images.githubusercontent.com/8571116/151367094-e77ecb54-7356-4c71-b920-92c4599fb0f6.png)
> 
> 
> 
> Dear JefNewTech,
> 
> 
> 
> did you try using your Boxx mobile app credentials ?

Yes

**Comment by HommiePeter** [comment]
Dear JefNewTech/Rereone, 

i'am afraid that Engie no longer supports requesting data via the Quby. Also on the home assistant platform issues with the Box from Engie in relation to the Toon integration gives similar issues. I am a afraid I will not be able to help you.

**Comment by rereone** [comment]
Hello,

Thanks for the research!

Renaud Dols
